development:
  adapter: postgresql
  encoding: unicode
  database: tada-ember
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: tada-ember
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: tada-ember
  pool: 5
  host: localhost
